// utils/slackReport.js — send daily team digest to Slack via incoming webhook
'use strict';

const https = require('https');
const { URL } = require('url');

// ── helpers ───────────────────────────────────────────────────────────────────

function fmtMins(mins) {
  if (!mins || mins <= 0) return '0m';
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return h > 0 ? `${h}h ${m > 0 ? m + 'm' : ''}`.trim() : `${m}m`;
}

function focusBar(score) {
  const filled = Math.round((score / 10) * 8);
  return '█'.repeat(filled) + '░'.repeat(8 - filled);
}

function focusEmoji(score) {
  if (score >= 8) return '🟢';
  if (score >= 5) return '🟡';
  return '🔴';
}

// POST JSON payload to a Slack incoming webhook URL
function postToSlack(webhookUrl, payload) {
  return new Promise((resolve, reject) => {
    const u    = new URL(webhookUrl);
    const body = JSON.stringify(payload);
    const req  = https.request({
      hostname: u.hostname,
      path:     u.pathname + u.search,
      method:   'POST',
      headers:  { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
    }, res => {
      let data = '';
      res.on('data', c => { data += c; });
      res.on('end', () => {
        if (res.statusCode === 200) resolve();
        else reject(new Error(`Slack webhook returned ${res.statusCode}: ${data}`));
      });
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

// ── build Slack Block Kit message ─────────────────────────────────────────────

function buildSlackPayload(date, employeeReports) {
  const dateLabel = new Date(date + 'T12:00:00').toLocaleDateString('en-US', {
    weekday: 'long', month: 'long', day: 'numeric',
  });

  const totalMins = employeeReports.reduce((s, r) => s + (r.report.total_tracked_minutes || 0), 0);
  const avgFocus  = employeeReports.length
    ? Math.round(employeeReports.reduce((s, r) => s + (r.report.ai_summary?.focusScore || 0), 0) / employeeReports.length)
    : 0;

  const blocks = [
    // ── Header ──────────────────────────────────────────────────────────────
    {
      type: 'header',
      text: { type: 'plain_text', text: `📊 Daily Team Report — ${dateLabel}`, emoji: true },
    },
    {
      type: 'context',
      elements: [{
        type: 'mrkdwn',
        text: `*${employeeReports.length} active*  ·  Team total *${fmtMins(totalMins)}*  ·  Avg focus *${avgFocus}/10*`,
      }],
    },
    { type: 'divider' },
  ];

  // ── Per-employee section ──────────────────────────────────────────────────
  for (const { employee, report } of employeeReports) {
    const ai      = report.ai_summary || {};
    const focus   = ai.focusScore ?? 0;
    const tracked = fmtMins(report.total_tracked_minutes);

    // Breaks
    const breaks       = report.breaks || [];
    const breakMins    = breaks.reduce((s, b) => s + (b.minutes || 0), 0);
    const breakLine    = breaks.length > 0
      ? `${breaks.length} break${breaks.length > 1 ? 's' : ''} · ${fmtMins(breakMins)} total`
      : 'No breaks';

    // Sessions
    const punchLog     = report.punch_log || [];
    const sessionCount = punchLog.length;

    // Task list
    const taskNames = [...new Set(punchLog.map(s => s.task_name || null).filter(Boolean))];
    const jiraItems = [...new Map(
      punchLog
        .filter(s => !s.task_name && s.jira_issue_key)
        .map(s => [s.jira_issue_summary || s.jira_issue_key, true])
    ).keys()];
    const taskLine = [
      ...taskNames.map(t => `• ${t}`),
      ...jiraItems.map(t => `• ${t}`),
    ].join('\n') || '• No specific task assigned';

    // Header row: name + stats
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*${employee.name}*  ${focusEmoji(focus)} ${tracked}  ·  Focus ${focus}/10  \`${focusBar(focus)}\``,
      },
    });

    // Stats row: sessions + breaks + productive %
    blocks.push({
      type: 'context',
      elements: [{ type: 'mrkdwn', text: `📋 ${sessionCount} session${sessionCount !== 1 ? 's' : ''}  ·  ☕ ${breakLine}  ·  ⚡ ${report.productive_percent ?? 0}% productive` }],
    });

    // Two-column: task list | AI summary
    blocks.push({
      type: 'section',
      fields: [
        { type: 'mrkdwn', text: `*Tasks:*\n${taskLine}` },
        { type: 'mrkdwn', text: ai.summary ? `*Summary:*\n_${ai.summary}_` : '_No summary available_' },
      ],
    });

    // Insight
    if (ai.insights) {
      blocks.push({
        type: 'context',
        elements: [{ type: 'mrkdwn', text: `💡 ${ai.insights}` }],
      });
    }

    blocks.push({ type: 'divider' });
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  blocks.push({
    type: 'context',
    elements: [{
      type: 'mrkdwn',
      text: `Generated by *TeamMonitor* · ${new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}`,
    }],
  });

  return { blocks };
}

// ── main export ───────────────────────────────────────────────────────────────

async function sendSlackReport(date, employeeReports) {
  const webhookUrl = process.env.SLACK_WEBHOOK_URL;
  if (!webhookUrl) {
    console.log('[slack] SLACK_WEBHOOK_URL not set — skipping');
    return;
  }
  if (!employeeReports.length) {
    console.log('[slack] No reports to send');
    return;
  }

  const payload = buildSlackPayload(date, employeeReports);
  await postToSlack(webhookUrl, payload);
  console.log(`[slack] Team digest sent for ${date} (${employeeReports.length} employees)`);
}

module.exports = { sendSlackReport };
